sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t 26121994667/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 26121994667/docker-react npm run test
